name: CI CD for react portfolio

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: write        

jobs: 
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Repository
            uses: actions/checkout@v3
            
          - name: Setup Node js
            uses: actions/checkout@v3
            with:
              node-version: 22.11.0

          - name: Install dependencies
            run: npm install    

          - name: Build Project
            run: react-scripts build 

          - name: Deploy to Github Pages
            uses: JamesIves/github-pages-deploy-action@v4
            with:
                branch: gh-pages
                folder: build